"""interests

Revision ID: a2d5edebeffc
Revises: 640f0ac53a7a
Create Date: 2024-12-11 11:56:30.697915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d5edebeffc'
down_revision: Union[str, None] = '640f0ac53a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_food_place',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_place_id'], ['food_place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'food_place_id')
    )
    op.create_table('user_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.alter_column('food_place', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_place', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('user_interests')
    op.drop_table('user_food_place')
    op.drop_table('interests')
    # ### end Alembic commands ###
